# Generated by Django 4.2.5 on 2023-09-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('stat_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('tournament_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('stage_slug', models.CharField(blank=True, max_length=100, null=True)),
                ('player_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gold_10', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gold_10_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tower_delta_10', models.IntegerField(blank=True, null=True)),
                ('tower_delta_10_count', models.IntegerField(blank=True, null=True)),
                ('gold_20', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gold_20_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tower_delta_20', models.IntegerField(blank=True, null=True)),
                ('tower_delta_20_count', models.IntegerField(blank=True, null=True)),
                ('win_time', models.PositiveBigIntegerField(blank=True, null=True)),
                ('win_count', models.IntegerField(blank=True, null=True)),
                ('lost_time', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lost_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_stats',
            },
        ),
    ]
