# Generated by Django 4.2.5 on 2023-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedTournaments',
            fields=[
                ('record_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tournament_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tournament_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recorded_tournaments',
            },
        ),
    ]
