# Generated by Django 4.2.5 on 2023-10-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_recordedtournaments'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='team_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
