# Generated by Django 4.2.5 on 2023-10-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_playerstats_role_playerstats_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='team_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
